// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum SMTCControlEvent {
  play,
  pause,
  previous,
  next,
  unknown,
  ;
}

class SMTCFlutter {
  const SMTCFlutter.raw();

  /// Apis for Flutter
  Future<void> close() =>
      RustLib.instance.api.crateApiSmtcFlutterNonWindowsImplSmtcFlutterClose(
        that: this,
      );

  /// Apis for Flutter
  factory SMTCFlutter() =>
      RustLib.instance.api.crateApiSmtcFlutterNonWindowsImplSmtcFlutterNew();

  /// Apis for Flutter
  Stream<SMTCControlEvent> subscribeToControlEvents() => RustLib.instance.api
          .crateApiSmtcFlutterNonWindowsImplSmtcFlutterSubscribeToControlEvents(
        that: this,
      );

  /// Apis for Flutter
  Future<void> updateDisplay(
          {required String title,
          required String artist,
          required String album,
          required int duration,
          required String path}) =>
      RustLib.instance.api
          .crateApiSmtcFlutterNonWindowsImplSmtcFlutterUpdateDisplay(
              that: this,
              title: title,
              artist: artist,
              album: album,
              duration: duration,
              path: path);

  /// Apis for Flutter
  Future<void> updateState({required SMTCState state}) => RustLib.instance.api
      .crateApiSmtcFlutterNonWindowsImplSmtcFlutterUpdateState(
          that: this, state: state);

  /// progress, duration: ms
  /// Apis for Flutter
  Future<void> updateTimeProperties({required int progress}) => RustLib
      .instance.api
      .crateApiSmtcFlutterNonWindowsImplSmtcFlutterUpdateTimeProperties(
          that: this, progress: progress);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SMTCFlutter && runtimeType == other.runtimeType;
}

enum SMTCState {
  paused,
  playing,
  ;
}
