// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 在非Windows平台上，该函数直接返回false
Future<bool> showInExplorer({required String path}) =>
    RustLib.instance.api.crateApiUtilsNonWindowsImplShowInExplorer(path: path);

/// 在非Windows平台上，该函数直接返回None
Future<String?> pickSingleFolder() =>
    RustLib.instance.api.crateApiUtilsNonWindowsImplPickSingleFolder();

/// 在非Windows平台上，该函数直接返回false
Future<bool> launchInBrowser({required String uri}) =>
    RustLib.instance.api.crateApiUtilsNonWindowsImplLaunchInBrowser(uri: uri);
