// This file re-exports the platform-specific utils implementation.
// On non-Windows platforms, it uses the non_windows_impl generated by frb 2.12.0.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

export 'utils/non_windows_impl.dart';
